# Generated by Django 5.0.1 on 2024-04-08 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='kdrama',
            fields=[
                ('kdrama_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('release_year', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdrama.character')),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('kdrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdrama.kdrama')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='kdrama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdrama.kdrama'),
        ),
        migrations.CreateModel(
            name='award',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('kdrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdrama.kdrama')),
            ],
        ),
        migrations.CreateModel(
            name='prod_company',
            fields=[
                ('prod_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('year_founded', models.CharField(blank=True, max_length=50)),
                ('kdrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdrama.kdrama')),
            ],
        ),
    ]
